baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Portfolio & Blogs'
theme = 'digitalgarden'


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 4
[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 5


[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/yanwcai'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'www.linkedin.com/in/yanwen-cai'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'stellar798@gmail.com'
  weight = 3